import { AppLogo } from "@/assets";
import type { Metadata } from "next";
import Image from "next/image";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <div className="not_allowed">
        <div>
          <Image src={AppLogo} alt="Not Allowed" height={250} width={250} />
        </div>
        <p className="title">This site doesn&apos;t support desktop view yet</p>
        <p className="paragraph">Please view on your mobile phone</p>
      </div>
      <div className="user">{children}</div>
    </>
  );
}
